<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>nullable</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CompraProgramada.Domain\CompraProgramada.Domain.csproj" />
    <ProjectReference Include="..\CompraProgramada.Application\CompraProgramada.Application.csproj" />
    <ProjectReference Include="..\CompraProgramada.Infrastructure\CompraProgramada.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
</Project>