// <auto-generated />
using System;
using CompraProgramada.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228061412_AddOrdemCompraEntity")]
    partial class AddOrdemCompraEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("CestaItem");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaTopFive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cestas");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("ValorMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CustodiaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CustodiaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaId");

                    b.ToTable("CustodiaItem");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.DistribuicaoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("DistribuicaoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DistribuicaoId");

                    b.ToTable("DistribuicaoItem");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Fracionario")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrdemCompraId1")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.HasIndex("OrdemCompraId1");

                    b.ToTable("OrdemCompraItem");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ValorMensalHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ValorMensalHistorico");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaItem", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.CestaTopFive", null)
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", null)
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramada.Domain.Entities.ContaGrafica", "ClienteId");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", null)
                        .WithOne("Custodia")
                        .HasForeignKey("CompraProgramada.Domain.Entities.Custodia", "ClienteId");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CustodiaItem", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Custodia", null)
                        .WithMany("Itens")
                        .HasForeignKey("CustodiaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.DistribuicaoItem", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Distribuicao", null)
                        .WithMany("Itens")
                        .HasForeignKey("DistribuicaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraItem", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.OrdemCompra", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany()
                        .HasForeignKey("OrdemCompraId1");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ValorMensalHistorico", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Cliente", null)
                        .WithMany("HistoricoValores")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaTopFive", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica")
                        .IsRequired();

                    b.Navigation("Custodia")
                        .IsRequired();

                    b.Navigation("HistoricoValores");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
